RSDKModding/Sonic-Mania-Decompilation

SonicMania/Objects/CPZ/ChemicalBall.c

`self->interval` is a uint8, so -128 is actually 128.

Fix ChemicalBall.c's interval literal.

---

SonicMania/Objects/Helpers/ReplayDB.c
SonicMania/Objects/Helpers/TimeAttackData.c
SonicMania/Objects/Menu/TimeAttackMenu.c
SonicMania/Objects/Menu/UIReplayCarousel.c

These mismatched value types and sizes cause bugs on big-endian CPUs. I've also replaced some hardcoded array sizes with `sizeof`, fixing one bugged size in the process.

User DB value size fixes

---

SonicMania/Objects/Global/Player.c

I've switched to a different constant to make the condition clearer and more consistent with other code.
In 4-player competition mode, player 4 couldn't be controlled. This fixes that.

Fix fourth player's input.

---

SonicMania/Objects/PGZ/PSZ2Outro.c

Ohhhhhhh where the hell do I begin with this...
Okay, so, if you complete PGZ2 while playing without Tails or Knuckles as a sidekick and while you have a Fire Shield, then the
game will crash during the cutscene right when the first 'pulse' of the Phantom Ruby happens.
This is caused by the shield being loaded into player 2's object slot. The cutscene tries to update both players, mistaking the shield for the sidekick character. This causes it to overwrite the shield's state with player state, causing the shield player pointer to be replaced with a pointer to a player object function. This would cause the shield object's update function to crash the game.
The original code was able to tell that the second player slot had a shield in it by comparing its classID to that of the first player, …

Fix crash in the PGZ2 outro.

---

SonicMania/Objects/Pinball/PBL_Crane.c

This fixes two bugs:
- If you get multiple different shields in the Combi Catcher, then the character may have a bugged 'null' shield upon returning to the level. This is caused by the IDs of the obtained shields being OR'd together, producing an invalid ID.
- In Mania Mode, the Combi Catcher occasionally should have 1UPs available, but an incorrect `RSDK::Rand` parameter was preventing it from doing so.
Both of these fixes have been verified against the assembly code of the latest Steam EXE.

Fix pinball bugs

---

SonicMania/Objects/Global/Player.c

The `tempHitbox` variable was only valid inside of the if, which lead to undefined behavior when using its address afterwards. While not an issue on MSVC, more aggressive compilers like GCC (O3) and Clang (O1) took advantage of this range limit to further optimize the code, and caused all sorts of bugs on Linux/Android.

Fix Insta-Shield hitbox

---

SonicMania/Objects/Menu/UIPicture.c

Fixed the graphical corruption happening in the rev01 Android and Switch video filter settings menu.
Closes https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/issues/171

Fix graphical corruption in the Android and Switch rev01 video filter menu

---

SonicMania/GameLink.h
SonicMania/Objects/FBZ/WarpDoor.c
SonicMania/Objects/MMZ/MatryoshkaBom.c

Some macros aren't available when building without editor support. Add `#ifdef RETRO_INCLUDE_EDITOR` to prevent compile errors.

Fix build when disabling the editor

---

SonicMania/Objects/SSZ/MSBomb.c

fixes an issue where the latter two MSBomb projectiles from Silver Sonic would go down instead of up like in the original game.
solves a part of https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/issues/184

fix Silver Sonic's MSBomb projectile

---

SonicMania/Objects/HPZ/Redz.c

The state would immediately get changed back to Walk, causing them to levitate.
Move the state change where it belongs.
Fixes #198.

Prevent Redz from flying

---

SonicMania/Objects/PGZ/JuggleSaw.c

Previous inaccurate behavior failed to decrement the sawTimer, making the badnik throw the saw instead of juggling it one more time.
Fixes #192.

Fix JuggleSaw juggle timer

---

SonicMania/Objects/SSZ/SilverSonic.c

This workaround should make it so that the compiler inlines Player_CheckAttacking while also removing the check on player->invincibleTimer. Partially addresses #184.

Prevent Silver Sonic from bouncing off of Super forms

---

SonicMania/Objects/Global/Player.c
SonicMania/Objects/Global/Player.h
SonicMania/Objects/LRZ/TurretSwitch.c
SonicMania/Objects/PGZ/DoorTrigger.c
SonicMania/Objects/SSZ/FlowerPod.c
SonicMania/Objects/SSZ/SilverSonic.c
SonicMania/PublicFunctions.c

Turns out multiple entities actually ignore the invincibilityTimer:
* SilverSonic
* TurretSwitch (Beta Lava Reef)
* DoorTrigger (PGZ1)
* FlowerPod (SSZ1)
Instead of doing the Silver Sonic workaround for Player_CheckAttacking, this commit creates a second function that specifically ignores invincibilityTimer.
Fixes #211.

Fix invalid Super form collisions

---

SonicMania/Objects/FBZ/WarpDoor.c
SonicMania/Objects/OOZ/Hatch.c

WarpDoor_Update was using relPosY instead of relPosX, making the warpdoor use an incorrect position (this possibly fixes many unreported issues). Rewrite part of Hatch_Create to account for fallthrough in the switch case. Fixes #212.

Fix Hatch/WarpDoor incorrect X position

---

SonicMania/Objects/ERZ/ERZOutro.c
SonicMania/Objects/HCZ/PullChain.c
SonicMania/Objects/Helpers/MathHelpers.c
SonicMania/Objects/LRZ/WalkerLegs.c
SonicMania/Objects/PGZ/PaperRoller.c

The square root computation ignores negative integers by simply dealing with it as an unsigned value.
Multiple parts of the code weren't using MathHelpers_Distance at all and were instead manually computing the distance. Refactor these computations to clean things up.
Fixes #225.

Math: Fix Sqrt helper and use Distance helper where appropriate

---

SonicMania/Objects/ERZ/ERZStart.c
SonicMania/Objects/ERZ/ERZStart.h
SonicMania/Objects/ERZ/PhantomKing.c
SonicMania/Objects/ERZ/PhantomKing.h
SonicMania/PublicFunctions.c

Add missing call to SetSpriteAnimation for the ruby. The phantom ruby oscillation routine keeps the decimal part of the fixed-point Y position.
Reorder the ERZStart_HandlePlayerHover parameters to match the original. Fix small typo in (Attatch-->Attach).
Fixes #230.

ERZStart/PhantomKing: Fix missing sprite animation and ruby offset

---

SonicMania/Objects/MSZ/SeeSaw.c

Currently SeeSaw_Update uses a switch case for targetTilt when it's meant to only check for SEESAW_TILT_M and launchVelocity causing #231 .
This PR fixes that (and technically adds unused orbTimer behavior)

Fix SeeSaw Orb landing

---

SonicMania/Objects/Pinball/PBL_Crane.c

It was 5 when it was supposed to be 6 of them.

Fix Podium count in the Pinball Bonus Stage

---

SonicMania/Objects/MMZ/Piston.c

Vertical and Horizontal reverse states set ACTIVE_BOUNDS to self->timer instead of self->active

Piston: Fix use of 'timer' instead of 'active'

---

SonicMania/Objects/LRZ/Drillerdroid.c
SonicMania/Objects/LRZ/Drillerdroid.h

* Fix not being able to kill the boss with a final rising lava hit (overwritten state)
* Fix incorrect indexes for drillPos/drillDelay
* Fix DRILLERDROIDO_MAIN case being used instead of DRILLERDROID_MAIN
* Fix misaligned struct
* Fix "stalatite" typo

LRZ: Make Drillerdroid more accurate

---

SonicMania/Objects/MSZ/MSZSetup.c

This causes Mirage Saloon act 1 background to display incorrectly compared to the steam version once the palette changes to midday.

[MSZ] Remove copy and pasted CopyPalette in MSZSetup_Create

---

SonicMania/Objects/ERZ/PhantomRuby.h

In PhantomRuby_Serialize, the actual type for sfx is uint8.
That sound effect would fail to play on big endian platforms (Wii/WiiU).

PhantomRuby: Fix sfx type

---

SonicMania/GameLink.h
SonicMania/Objects/AIZ/FernParallax.c
SonicMania/Objects/AIZ/FernParallax.h
SonicMania/Objects/AIZ/SchrodingersCapsule.c
SonicMania/Objects/Global/Player.c
SonicMania/Objects/Global/TitleCard.c
SonicMania/Objects/Global/Zone.c
SonicMania/Objects/Global/Zone.h

This struct is used Engine-side as a generic Entity type that can hold the data for any game Entity.
v5U added an extra void* field to it, making the ENTITY_SIZE macro incorrect.
Use EntityBase in some parts of the code that were using some kind of uint8 entity buffer array.
This reduces type cast alignment issues while also making the Mania code more compatible with v5U.

GameLink: Add/Use EntityBase struct

---

README.md

This carries over some of the improvements to the CMake documentation/building instructions made in the RSDKv3 and RSDKv4 repositories, and generally cleans up some minor things.

CMake documentation improvements

---

SonicMania/Objects/MSZ/MSZSetup.c
SonicMania/Objects/Menu/UIVsCharSelector.c
SonicMania/SonicMania_All.vcxproj
SonicMania/SonicMania_All.vcxproj.filters
SonicMania/SonicMania_All_PrePlus.vcxproj
SonicMania/SonicMania_All_PrePlus.vcxproj.filters
SonicMania/SonicMania_All_Rev0U.vcxproj
SonicMania/SonicMania_All_Rev0U.vcxproj.filters

this pull request may close the following issues:
#267 - Not selecting the same character in PrePlus versions of the game
#268 - Mirage Saloon Zone Act 1's background palette not changing.
#269 - a version resource file not available within the "All" configs of the Visual Studio projects.
while not pushed to the main repo yet, I believe that this should be a quick way to take care of them entirely, alongside avoiding potential future issues in the long run.

Minor fixes to certain parts of the decomp's code

---

SonicMania/Objects/Global/Ring.c

Fixes a bug in Ring_CheckObjectCollisions that prevented lost rings from interacting with collisionSides
Current behavior - notice how the rings stop moving on the decomp
https://github.com/user-attachments/assets/976d31fb-4055-495f-a8b7-f9e968ac6da5
Fixed behavior -
https://github.com/user-attachments/assets/dd14bb92-fead-4076-9bc8-e191fb04e175
Tested on both v5 & v5U

Fix Ring_CheckObjectCollisions

---

SonicMania/Objects/Global/Player.c

Fixes an issue on Player_State_KnuxWallClimb that prevented the player from correctly launching from a jump underwater
Water_State_Water will set player->underwater to an entity slot. For KnuxWallClimb, the state incorrectly checks for `if (self->underwater != 0)` instead of `if (self->underwater == 1)`
Current behavior:
https://github.com/user-attachments/assets/9a474787-2214-41c8-ae62-6126d2282ae8
Fixed behavior:
https://github.com/user-attachments/assets/4642d5ae-8237-42aa-8915-5d3842fc5fd9
Fixes #313

Fix incorrect self->underwater check in Player_State_KnuxWallClimb
