RSDKModding/Sonic-Mania-Decompilation

SonicMania/Objects/Helpers/Options.c
This makes it clearer which platforms this code runs on.
The edit to that first line is just for consistency with the others.
=> Deobfuscate some platform checks in `Options.c`.

SonicMania/GameLink.h, SonicMania/Objects/FBZ/FoldingPlatform.h, SonicMania/Objects/LRZ/HPZEmerald.h
See the commit descriptions for more information.
=> Fix a softlock and some build warnings.

README.md
Merge the last two questions in the Q&A together (they were basically asking the same thing)
=> The readme if it was good

SonicMania/Objects/Global/Zone.c
This avoids some awkward casting an indexing, and is likely closer to the original source code.
=> Correct some funky decompiled logic relating to layers.

SonicMania/Objects/SSZ/Fireflies.c
A bunch of decompiled code was missing. Because of this, the fireflies would all be flying around wildly at the top left of the level.
Before:
After:
=> Fix SSZ fireflies.

SonicMania/Objects/Global/APICallback.c, SonicMania/Objects/Menu/MenuSetup.c, SonicMania/Objects/Menu/UITAZoneModule.c, SonicMania/Objects/Menu/UIText.c
These parameters measure the length of the input string.
=> Correct `InitString` parameters.

SonicMania/Objects/Global/ItemBox.c
=> fix itembox content render not updating.

LICENSE.md, README.md
=> linux instructions

SonicMania/GameLink.h
Allows platforms to redefine them at compile time.
=> Wrap SCREEN_XMAX, SCREEN_YSIZE and SCREEN_COUNT in #ifndef

SonicMania/Objects/Global/TimeAttackGate.c, SonicMania/Objects/Global/TimeAttackGate.h
=> Fix camera panning on Goal in Time Attack mode

SonicMania/Objects/SSZ/MetalSonic.c
=> SSZ3: Prevent StarPost stars from growing indefinitely

SonicMania/Objects/SSZ/HotaruMKII.c
=> Fix HotaruMKII not attacking when the player is too fast

SonicMania/Objects/OOZ/MegaOctus.c
=> MegaOctus: Fix buggy collisions when platform rises from oil

SonicMania/Objects/Global/Player.c
=> Fix sidekick jumping uncontrollably instead of pushing

SonicMania/Objects/Menu/UIBackground.c
i think this was a copy+paste issue probs
=> Fix UI Background using an inner circle for one of the Orange Circles

SonicMania/Objects/TMZ/GymBar.c
thanks for pointing this out Axanery 👍
=> fix gymbar typo in GymBar_HandleSwingJump

SonicMania/Objects/OOZ/PullSwitch.c
=> PullSwitch: Fix inaccurate collision

SonicMania/Objects/MMZ/BuzzSaw.c, SonicMania/Objects/MMZ/BuzzSaw.h, SonicMania/Objects/MMZ/Gachapandora.c, SonicMania/Objects/MMZ/Gachapandora.h, SonicMania/Objects/SSZ/Bungee.c, SonicMania/Objects/SSZ/Bungee.h, SonicMania/Objects/TMZ/SentryBug.c, SonicMania/Objects/TMZ/SentryBug.h, SonicMania/PublicFunctions.c
=> Fix Attached Detached typos

SonicMania/Objects/Global/Spikes.c, SonicMania/Objects/Global/Spikes.h, SonicMania/PublicFunctions.c
Spike_Draw_Stage -> Spike_Draw_Global (these two were mixed up)
Spike_Draw_Global -> Spike_Draw_Glint
=> [Spikes] change Spike_Draw names

README.md
A dumb change that just removes a broken 404 link.
=> Remove broken Origin store link from README.md

SonicMania/Objects/Common/BreakableWall.c
Fixes #275 - along with two other minor issues with knux/mighty
=> Fix BreakableWall collision behavior

SonicMania/Objects/Common/Water.c
=> Fix Water_State_Bubbler's rand behavior
